/* automatically generated by rust-bindgen 0.72.1 */

use crate::*;

pub const GGUF_TYPE_UINT8: gguf_type = 0;
pub const GGUF_TYPE_INT8: gguf_type = 1;
pub const GGUF_TYPE_UINT16: gguf_type = 2;
pub const GGUF_TYPE_INT16: gguf_type = 3;
pub const GGUF_TYPE_UINT32: gguf_type = 4;
pub const GGUF_TYPE_INT32: gguf_type = 5;
pub const GGUF_TYPE_FLOAT32: gguf_type = 6;
pub const GGUF_TYPE_BOOL: gguf_type = 7;
pub const GGUF_TYPE_STRING: gguf_type = 8;
pub const GGUF_TYPE_ARRAY: gguf_type = 9;
pub const GGUF_TYPE_UINT64: gguf_type = 10;
pub const GGUF_TYPE_INT64: gguf_type = 11;
pub const GGUF_TYPE_FLOAT64: gguf_type = 12;
pub const GGUF_TYPE_COUNT: gguf_type = 13;
pub type gguf_type = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gguf_context {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct gguf_init_params {
    pub no_alloc: bool,
    pub ctx: *mut *mut ggml_context,
}
pub type gguf_reader_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::std::os::raw::c_void,
        output: *mut ::std::os::raw::c_void,
        offset: u64,
        len: usize,
    ) -> usize,
>;
extern "C" {
    pub fn gguf_init_empty() -> *mut gguf_context;
}
extern "C" {
    pub fn gguf_init_from_file_ptr(file: *mut FILE, params: gguf_init_params) -> *mut gguf_context;
}
extern "C" {
    pub fn gguf_init_from_file(
        fname: *const ::std::os::raw::c_char,
        params: gguf_init_params,
    ) -> *mut gguf_context;
}
extern "C" {
    pub fn gguf_init_from_buffer(
        data: *const ::std::os::raw::c_void,
        size: usize,
        params: gguf_init_params,
    ) -> *mut gguf_context;
}
extern "C" {
    pub fn gguf_init_from_callback(
        callback: gguf_reader_callback_t,
        userdata: *mut ::std::os::raw::c_void,
        max_chunk_read: usize,
        max_expected_size: u64,
        params: gguf_init_params,
    ) -> *mut gguf_context;
}
extern "C" {
    pub fn gguf_free(ctx: *mut gguf_context);
}
extern "C" {
    pub fn gguf_type_name(type_: gguf_type) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn gguf_get_version(ctx: *const gguf_context) -> u32;
}
extern "C" {
    pub fn gguf_get_alignment(ctx: *const gguf_context) -> usize;
}
extern "C" {
    pub fn gguf_get_data_offset(ctx: *const gguf_context) -> usize;
}
extern "C" {
    pub fn gguf_get_n_kv(ctx: *const gguf_context) -> i64;
}
extern "C" {
    pub fn gguf_find_key(ctx: *const gguf_context, key: *const ::std::os::raw::c_char) -> i64;
}
extern "C" {
    pub fn gguf_get_key(ctx: *const gguf_context, key_id: i64) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn gguf_get_kv_type(ctx: *const gguf_context, key_id: i64) -> gguf_type;
}
extern "C" {
    pub fn gguf_get_arr_type(ctx: *const gguf_context, key_id: i64) -> gguf_type;
}
extern "C" {
    pub fn gguf_get_val_u8(ctx: *const gguf_context, key_id: i64) -> u8;
}
extern "C" {
    pub fn gguf_get_val_i8(ctx: *const gguf_context, key_id: i64) -> i8;
}
extern "C" {
    pub fn gguf_get_val_u16(ctx: *const gguf_context, key_id: i64) -> u16;
}
extern "C" {
    pub fn gguf_get_val_i16(ctx: *const gguf_context, key_id: i64) -> i16;
}
extern "C" {
    pub fn gguf_get_val_u32(ctx: *const gguf_context, key_id: i64) -> u32;
}
extern "C" {
    pub fn gguf_get_val_i32(ctx: *const gguf_context, key_id: i64) -> i32;
}
extern "C" {
    pub fn gguf_get_val_f32(ctx: *const gguf_context, key_id: i64) -> f32;
}
extern "C" {
    pub fn gguf_get_val_u64(ctx: *const gguf_context, key_id: i64) -> u64;
}
extern "C" {
    pub fn gguf_get_val_i64(ctx: *const gguf_context, key_id: i64) -> i64;
}
extern "C" {
    pub fn gguf_get_val_f64(ctx: *const gguf_context, key_id: i64) -> f64;
}
extern "C" {
    pub fn gguf_get_val_bool(ctx: *const gguf_context, key_id: i64) -> bool;
}
extern "C" {
    pub fn gguf_get_val_str(ctx: *const gguf_context, key_id: i64)
        -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn gguf_get_val_data(
        ctx: *const gguf_context,
        key_id: i64,
    ) -> *const ::std::os::raw::c_void;
}
extern "C" {
    pub fn gguf_get_arr_n(ctx: *const gguf_context, key_id: i64) -> usize;
}
extern "C" {
    pub fn gguf_get_arr_data(
        ctx: *const gguf_context,
        key_id: i64,
    ) -> *const ::std::os::raw::c_void;
}
extern "C" {
    pub fn gguf_get_arr_str(
        ctx: *const gguf_context,
        key_id: i64,
        i: usize,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn gguf_get_n_tensors(ctx: *const gguf_context) -> i64;
}
extern "C" {
    pub fn gguf_find_tensor(ctx: *const gguf_context, name: *const ::std::os::raw::c_char) -> i64;
}
extern "C" {
    pub fn gguf_get_tensor_offset(ctx: *const gguf_context, tensor_id: i64) -> usize;
}
extern "C" {
    pub fn gguf_get_tensor_name(
        ctx: *const gguf_context,
        tensor_id: i64,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn gguf_get_tensor_ne(ctx: *const gguf_context, tensor_id: i64) -> *const i64;
}
extern "C" {
    pub fn gguf_get_tensor_type(ctx: *const gguf_context, tensor_id: i64) -> ggml_type;
}
extern "C" {
    pub fn gguf_get_tensor_size(ctx: *const gguf_context, tensor_id: i64) -> usize;
}
extern "C" {
    pub fn gguf_remove_key(ctx: *mut gguf_context, key: *const ::std::os::raw::c_char) -> i64;
}
extern "C" {
    pub fn gguf_set_val_u8(ctx: *mut gguf_context, key: *const ::std::os::raw::c_char, val: u8);
}
extern "C" {
    pub fn gguf_set_val_i8(ctx: *mut gguf_context, key: *const ::std::os::raw::c_char, val: i8);
}
extern "C" {
    pub fn gguf_set_val_u16(ctx: *mut gguf_context, key: *const ::std::os::raw::c_char, val: u16);
}
extern "C" {
    pub fn gguf_set_val_i16(ctx: *mut gguf_context, key: *const ::std::os::raw::c_char, val: i16);
}
extern "C" {
    pub fn gguf_set_val_u32(ctx: *mut gguf_context, key: *const ::std::os::raw::c_char, val: u32);
}
extern "C" {
    pub fn gguf_set_val_i32(ctx: *mut gguf_context, key: *const ::std::os::raw::c_char, val: i32);
}
extern "C" {
    pub fn gguf_set_val_f32(ctx: *mut gguf_context, key: *const ::std::os::raw::c_char, val: f32);
}
extern "C" {
    pub fn gguf_set_val_u64(ctx: *mut gguf_context, key: *const ::std::os::raw::c_char, val: u64);
}
extern "C" {
    pub fn gguf_set_val_i64(ctx: *mut gguf_context, key: *const ::std::os::raw::c_char, val: i64);
}
extern "C" {
    pub fn gguf_set_val_f64(ctx: *mut gguf_context, key: *const ::std::os::raw::c_char, val: f64);
}
extern "C" {
    pub fn gguf_set_val_bool(ctx: *mut gguf_context, key: *const ::std::os::raw::c_char, val: bool);
}
extern "C" {
    pub fn gguf_set_val_str(
        ctx: *mut gguf_context,
        key: *const ::std::os::raw::c_char,
        val: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn gguf_set_arr_data(
        ctx: *mut gguf_context,
        key: *const ::std::os::raw::c_char,
        type_: gguf_type,
        data: *const ::std::os::raw::c_void,
        n: usize,
    );
}
extern "C" {
    pub fn gguf_set_arr_str(
        ctx: *mut gguf_context,
        key: *const ::std::os::raw::c_char,
        data: *mut *const ::std::os::raw::c_char,
        n: usize,
    );
}
extern "C" {
    pub fn gguf_set_kv(ctx: *mut gguf_context, src: *const gguf_context);
}
extern "C" {
    pub fn gguf_add_tensor(ctx: *mut gguf_context, tensor: *const ggml_tensor);
}
extern "C" {
    pub fn gguf_set_tensor_type(
        ctx: *mut gguf_context,
        name: *const ::std::os::raw::c_char,
        type_: ggml_type,
    );
}
extern "C" {
    pub fn gguf_set_tensor_data(
        ctx: *mut gguf_context,
        name: *const ::std::os::raw::c_char,
        data: *const ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn gguf_write_to_file_ptr(
        ctx: *const gguf_context,
        file: *mut FILE,
        only_meta: bool,
    ) -> bool;
}
extern "C" {
    pub fn gguf_write_to_file(
        ctx: *const gguf_context,
        fname: *const ::std::os::raw::c_char,
        only_meta: bool,
    ) -> bool;
}
extern "C" {
    pub fn gguf_get_meta_size(ctx: *const gguf_context) -> usize;
}
extern "C" {
    pub fn gguf_get_meta_data(ctx: *const gguf_context, data: *mut ::std::os::raw::c_void);
}
