/* automatically generated by rust-bindgen 0.72.1 */

use crate::*;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_vocab {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_model {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_context {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_memory_i {
    _unused: [u8; 0],
}
pub type llama_memory_t = *mut llama_memory_i;
pub type llama_pos = i32;
pub type llama_token = i32;
pub type llama_seq_id = i32;
pub const LLAMA_VOCAB_TYPE_NONE: llama_vocab_type = 0;
pub const LLAMA_VOCAB_TYPE_SPM: llama_vocab_type = 1;
pub const LLAMA_VOCAB_TYPE_BPE: llama_vocab_type = 2;
pub const LLAMA_VOCAB_TYPE_WPM: llama_vocab_type = 3;
pub const LLAMA_VOCAB_TYPE_UGM: llama_vocab_type = 4;
pub const LLAMA_VOCAB_TYPE_RWKV: llama_vocab_type = 5;
pub const LLAMA_VOCAB_TYPE_PLAMO2: llama_vocab_type = 6;
pub type llama_vocab_type = ::std::os::raw::c_uint;
pub const LLAMA_ROPE_TYPE_NONE: llama_rope_type = -1;
pub const LLAMA_ROPE_TYPE_NORM: llama_rope_type = 0;
pub const LLAMA_ROPE_TYPE_NEOX: llama_rope_type = 2;
pub const LLAMA_ROPE_TYPE_MROPE: llama_rope_type = 8;
pub const LLAMA_ROPE_TYPE_IMROPE: llama_rope_type = 40;
pub const LLAMA_ROPE_TYPE_VISION: llama_rope_type = 24;
pub type llama_rope_type = ::std::os::raw::c_int;
pub const LLAMA_TOKEN_TYPE_UNDEFINED: llama_token_type = 0;
pub const LLAMA_TOKEN_TYPE_NORMAL: llama_token_type = 1;
pub const LLAMA_TOKEN_TYPE_UNKNOWN: llama_token_type = 2;
pub const LLAMA_TOKEN_TYPE_CONTROL: llama_token_type = 3;
pub const LLAMA_TOKEN_TYPE_USER_DEFINED: llama_token_type = 4;
pub const LLAMA_TOKEN_TYPE_UNUSED: llama_token_type = 5;
pub const LLAMA_TOKEN_TYPE_BYTE: llama_token_type = 6;
pub type llama_token_type = ::std::os::raw::c_uint;
pub const LLAMA_TOKEN_ATTR_UNDEFINED: llama_token_attr = 0;
pub const LLAMA_TOKEN_ATTR_UNKNOWN: llama_token_attr = 1;
pub const LLAMA_TOKEN_ATTR_UNUSED: llama_token_attr = 2;
pub const LLAMA_TOKEN_ATTR_NORMAL: llama_token_attr = 4;
pub const LLAMA_TOKEN_ATTR_CONTROL: llama_token_attr = 8;
pub const LLAMA_TOKEN_ATTR_USER_DEFINED: llama_token_attr = 16;
pub const LLAMA_TOKEN_ATTR_BYTE: llama_token_attr = 32;
pub const LLAMA_TOKEN_ATTR_NORMALIZED: llama_token_attr = 64;
pub const LLAMA_TOKEN_ATTR_LSTRIP: llama_token_attr = 128;
pub const LLAMA_TOKEN_ATTR_RSTRIP: llama_token_attr = 256;
pub const LLAMA_TOKEN_ATTR_SINGLE_WORD: llama_token_attr = 512;
pub type llama_token_attr = ::std::os::raw::c_uint;
pub const LLAMA_FTYPE_ALL_F32: llama_ftype = 0;
pub const LLAMA_FTYPE_MOSTLY_F16: llama_ftype = 1;
pub const LLAMA_FTYPE_MOSTLY_Q4_0: llama_ftype = 2;
pub const LLAMA_FTYPE_MOSTLY_Q4_1: llama_ftype = 3;
pub const LLAMA_FTYPE_MOSTLY_Q8_0: llama_ftype = 7;
pub const LLAMA_FTYPE_MOSTLY_Q5_0: llama_ftype = 8;
pub const LLAMA_FTYPE_MOSTLY_Q5_1: llama_ftype = 9;
pub const LLAMA_FTYPE_MOSTLY_Q2_K: llama_ftype = 10;
pub const LLAMA_FTYPE_MOSTLY_Q3_K_S: llama_ftype = 11;
pub const LLAMA_FTYPE_MOSTLY_Q3_K_M: llama_ftype = 12;
pub const LLAMA_FTYPE_MOSTLY_Q3_K_L: llama_ftype = 13;
pub const LLAMA_FTYPE_MOSTLY_Q4_K_S: llama_ftype = 14;
pub const LLAMA_FTYPE_MOSTLY_Q4_K_M: llama_ftype = 15;
pub const LLAMA_FTYPE_MOSTLY_Q5_K_S: llama_ftype = 16;
pub const LLAMA_FTYPE_MOSTLY_Q5_K_M: llama_ftype = 17;
pub const LLAMA_FTYPE_MOSTLY_Q6_K: llama_ftype = 18;
pub const LLAMA_FTYPE_MOSTLY_IQ2_XXS: llama_ftype = 19;
pub const LLAMA_FTYPE_MOSTLY_IQ2_XS: llama_ftype = 20;
pub const LLAMA_FTYPE_MOSTLY_Q2_K_S: llama_ftype = 21;
pub const LLAMA_FTYPE_MOSTLY_IQ3_XS: llama_ftype = 22;
pub const LLAMA_FTYPE_MOSTLY_IQ3_XXS: llama_ftype = 23;
pub const LLAMA_FTYPE_MOSTLY_IQ1_S: llama_ftype = 24;
pub const LLAMA_FTYPE_MOSTLY_IQ4_NL: llama_ftype = 25;
pub const LLAMA_FTYPE_MOSTLY_IQ3_S: llama_ftype = 26;
pub const LLAMA_FTYPE_MOSTLY_IQ3_M: llama_ftype = 27;
pub const LLAMA_FTYPE_MOSTLY_IQ2_S: llama_ftype = 28;
pub const LLAMA_FTYPE_MOSTLY_IQ2_M: llama_ftype = 29;
pub const LLAMA_FTYPE_MOSTLY_IQ4_XS: llama_ftype = 30;
pub const LLAMA_FTYPE_MOSTLY_IQ1_M: llama_ftype = 31;
pub const LLAMA_FTYPE_MOSTLY_BF16: llama_ftype = 32;
pub const LLAMA_FTYPE_MOSTLY_TQ1_0: llama_ftype = 36;
pub const LLAMA_FTYPE_MOSTLY_TQ2_0: llama_ftype = 37;
pub const LLAMA_FTYPE_MOSTLY_MXFP4_MOE: llama_ftype = 38;
pub const LLAMA_FTYPE_MOSTLY_NVFP4: llama_ftype = 39;
pub const LLAMA_FTYPE_MOSTLY_Q1_0: llama_ftype = 40;
pub const LLAMA_FTYPE_MOSTLY_Q2_0: llama_ftype = 41;
pub const LLAMA_FTYPE_GUESSED: llama_ftype = 1024;
pub type llama_ftype = ::std::os::raw::c_uint;
extern "C" {
    pub fn llama_ftype_name(ftype: llama_ftype) -> *const ::std::os::raw::c_char;
}
pub const LLAMA_ROPE_SCALING_TYPE_UNSPECIFIED: llama_rope_scaling_type = -1;
pub const LLAMA_ROPE_SCALING_TYPE_NONE: llama_rope_scaling_type = 0;
pub const LLAMA_ROPE_SCALING_TYPE_LINEAR: llama_rope_scaling_type = 1;
pub const LLAMA_ROPE_SCALING_TYPE_YARN: llama_rope_scaling_type = 2;
pub const LLAMA_ROPE_SCALING_TYPE_LONGROPE: llama_rope_scaling_type = 3;
pub const LLAMA_ROPE_SCALING_TYPE_MAX_VALUE: llama_rope_scaling_type = 3;
pub type llama_rope_scaling_type = ::std::os::raw::c_int;
pub const LLAMA_POOLING_TYPE_UNSPECIFIED: llama_pooling_type = -1;
pub const LLAMA_POOLING_TYPE_NONE: llama_pooling_type = 0;
pub const LLAMA_POOLING_TYPE_MEAN: llama_pooling_type = 1;
pub const LLAMA_POOLING_TYPE_CLS: llama_pooling_type = 2;
pub const LLAMA_POOLING_TYPE_LAST: llama_pooling_type = 3;
pub const LLAMA_POOLING_TYPE_RANK: llama_pooling_type = 4;
pub type llama_pooling_type = ::std::os::raw::c_int;
pub const LLAMA_ATTENTION_TYPE_UNSPECIFIED: llama_attention_type = -1;
pub const LLAMA_ATTENTION_TYPE_CAUSAL: llama_attention_type = 0;
pub const LLAMA_ATTENTION_TYPE_NON_CAUSAL: llama_attention_type = 1;
pub type llama_attention_type = ::std::os::raw::c_int;
pub const LLAMA_FLASH_ATTN_TYPE_AUTO: llama_flash_attn_type = -1;
pub const LLAMA_FLASH_ATTN_TYPE_DISABLED: llama_flash_attn_type = 0;
pub const LLAMA_FLASH_ATTN_TYPE_ENABLED: llama_flash_attn_type = 1;
pub type llama_flash_attn_type = ::std::os::raw::c_int;
extern "C" {
    pub fn llama_flash_attn_type_name(
        flash_attn_type: llama_flash_attn_type,
    ) -> *const ::std::os::raw::c_char;
}
pub const LLAMA_SPLIT_MODE_NONE: llama_split_mode = 0;
pub const LLAMA_SPLIT_MODE_LAYER: llama_split_mode = 1;
pub const LLAMA_SPLIT_MODE_ROW: llama_split_mode = 2;
pub const LLAMA_SPLIT_MODE_TENSOR: llama_split_mode = 3;
pub type llama_split_mode = ::std::os::raw::c_uint;
pub const LLAMA_LOAD_MODE_AUTO: llama_load_mode = -1;
pub const LLAMA_LOAD_MODE_NONE: llama_load_mode = 0;
pub const LLAMA_LOAD_MODE_MMAP: llama_load_mode = 1;
pub const LLAMA_LOAD_MODE_MLOCK: llama_load_mode = 2;
pub const LLAMA_LOAD_MODE_MMAP_MLOCK: llama_load_mode = 3;
pub const LLAMA_LOAD_MODE_DIRECT_IO: llama_load_mode = 4;
pub type llama_load_mode = ::std::os::raw::c_int;
extern "C" {
    pub fn llama_load_mode_name(load_mode: llama_load_mode) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn llama_load_mode_from_str(str_: *const ::std::os::raw::c_char) -> llama_load_mode;
}
pub const LLAMA_CONTEXT_TYPE_DEFAULT: llama_context_type = 0;
pub const LLAMA_CONTEXT_TYPE_MTP: llama_context_type = 1;
pub type llama_context_type = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_token_data {
    pub id: llama_token,
    pub logit: f32,
    pub p: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_token_data_array {
    pub data: *mut llama_token_data,
    pub size: usize,
    pub selected: i64,
    pub sorted: bool,
}
pub type llama_progress_callback = ::std::option::Option<
    unsafe extern "C" fn(progress: f32, user_data: *mut ::std::os::raw::c_void) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_batch {
    pub n_tokens: i32,
    pub token: *mut llama_token,
    pub embd: *mut f32,
    pub pos: *mut llama_pos,
    pub n_seq_id: *mut i32,
    pub seq_id: *mut *mut llama_seq_id,
    pub logits: *mut i8,
}
pub const LLAMA_KV_OVERRIDE_TYPE_INT: llama_model_kv_override_type = 0;
pub const LLAMA_KV_OVERRIDE_TYPE_FLOAT: llama_model_kv_override_type = 1;
pub const LLAMA_KV_OVERRIDE_TYPE_BOOL: llama_model_kv_override_type = 2;
pub const LLAMA_KV_OVERRIDE_TYPE_STR: llama_model_kv_override_type = 3;
pub type llama_model_kv_override_type = ::std::os::raw::c_uint;
pub const LLAMA_MODEL_META_KEY_SAMPLING_SEQUENCE: llama_model_meta_key = 0;
pub const LLAMA_MODEL_META_KEY_SAMPLING_TOP_K: llama_model_meta_key = 1;
pub const LLAMA_MODEL_META_KEY_SAMPLING_TOP_P: llama_model_meta_key = 2;
pub const LLAMA_MODEL_META_KEY_SAMPLING_MIN_P: llama_model_meta_key = 3;
pub const LLAMA_MODEL_META_KEY_SAMPLING_XTC_PROBABILITY: llama_model_meta_key = 4;
pub const LLAMA_MODEL_META_KEY_SAMPLING_XTC_THRESHOLD: llama_model_meta_key = 5;
pub const LLAMA_MODEL_META_KEY_SAMPLING_TEMP: llama_model_meta_key = 6;
pub const LLAMA_MODEL_META_KEY_SAMPLING_PENALTY_LAST_N: llama_model_meta_key = 7;
pub const LLAMA_MODEL_META_KEY_SAMPLING_PENALTY_REPEAT: llama_model_meta_key = 8;
pub const LLAMA_MODEL_META_KEY_SAMPLING_MIROSTAT: llama_model_meta_key = 9;
pub const LLAMA_MODEL_META_KEY_SAMPLING_MIROSTAT_TAU: llama_model_meta_key = 10;
pub const LLAMA_MODEL_META_KEY_SAMPLING_MIROSTAT_ETA: llama_model_meta_key = 11;
pub type llama_model_meta_key = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct llama_model_kv_override {
    pub tag: llama_model_kv_override_type,
    pub key: [::std::os::raw::c_char; 128usize],
    pub __bindgen_anon_1: llama_model_kv_override__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union llama_model_kv_override__bindgen_ty_1 {
    pub val_i64: i64,
    pub val_f64: f64,
    pub val_bool: bool,
    pub val_str: [::std::os::raw::c_char; 128usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_model_tensor_buft_override {
    pub pattern: *const ::std::os::raw::c_char,
    pub buft: ggml_backend_buffer_type_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_model_params {
    pub devices: *mut ggml_backend_dev_t,
    pub tensor_buft_overrides: *const llama_model_tensor_buft_override,
    pub n_gpu_layers: i32,
    pub split_mode: llama_split_mode,
    pub load_mode: llama_load_mode,
    pub main_gpu: i32,
    pub tensor_split: *const f32,
    pub progress_callback: llama_progress_callback,
    pub progress_callback_user_data: *mut ::std::os::raw::c_void,
    pub kv_overrides: *const llama_model_kv_override,
    pub vocab_only: bool,
    pub check_tensors: bool,
    pub use_extra_bufts: bool,
    pub no_host: bool,
    pub no_alloc: bool,
    pub load_mtp: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_sampler_seq_config {
    pub seq_id: llama_seq_id,
    pub sampler: *mut llama_sampler,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_context_params {
    pub n_ctx: u32,
    pub n_batch: u32,
    pub n_ubatch: u32,
    pub n_seq_max: u32,
    pub n_rs_seq: u32,
    pub n_outputs_max: u32,
    pub n_outputs_max_per_seq: u32,
    pub n_threads: i32,
    pub n_threads_batch: i32,
    pub ctx_type: llama_context_type,
    pub rope_scaling_type: llama_rope_scaling_type,
    pub pooling_type: llama_pooling_type,
    pub attention_type: llama_attention_type,
    pub flash_attn_type: llama_flash_attn_type,
    pub rope_freq_base: f32,
    pub rope_freq_scale: f32,
    pub yarn_ext_factor: f32,
    pub yarn_attn_factor: f32,
    pub yarn_beta_fast: f32,
    pub yarn_beta_slow: f32,
    pub yarn_orig_ctx: u32,
    pub defrag_thold: f32,
    pub cb_eval: ggml_backend_sched_eval_callback,
    pub cb_eval_user_data: *mut ::std::os::raw::c_void,
    pub type_k: ggml_type,
    pub type_v: ggml_type,
    pub abort_callback: ggml_abort_callback,
    pub abort_callback_data: *mut ::std::os::raw::c_void,
    pub embeddings: bool,
    pub offload_kqv: bool,
    pub no_perf: bool,
    pub op_offload: bool,
    pub swa_full: bool,
    pub kv_unified: bool,
    pub samplers: *mut llama_sampler_seq_config,
    pub n_samplers: usize,
    pub ctx_other: *mut llama_context,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_model_tensor_override {
    pub pattern: *const ::std::os::raw::c_char,
    pub type_: ggml_type,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_model_imatrix_data {
    pub name: *const ::std::os::raw::c_char,
    pub data: *const f32,
    pub size: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_model_quantize_params {
    pub nthread: i32,
    pub ftype: llama_ftype,
    pub output_tensor_type: ggml_type,
    pub token_embedding_type: ggml_type,
    pub allow_requantize: bool,
    pub quantize_output_tensor: bool,
    pub only_copy: bool,
    pub pure_: bool,
    pub keep_split: bool,
    pub dry_run: bool,
    pub imatrix: *const llama_model_imatrix_data,
    pub kv_overrides: *const llama_model_kv_override,
    pub tt_overrides: *const llama_model_tensor_override,
    pub prune_layers: *const i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_logit_bias {
    pub token: llama_token,
    pub bias: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_sampler_chain_params {
    pub no_perf: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_chat_message {
    pub role: *const ::std::os::raw::c_char,
    pub content: *const ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_adapter_lora {
    _unused: [u8; 0],
}
extern "C" {
    pub fn llama_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn llama_model_default_params() -> llama_model_params;
}
extern "C" {
    pub fn llama_context_default_params() -> llama_context_params;
}
extern "C" {
    pub fn llama_sampler_chain_default_params() -> llama_sampler_chain_params;
}
extern "C" {
    pub fn llama_model_quantize_default_params() -> llama_model_quantize_params;
}
extern "C" {
    pub fn llama_backend_init();
}
extern "C" {
    pub fn llama_backend_free();
}
extern "C" {
    pub fn llama_numa_init(numa: ggml_numa_strategy);
}
extern "C" {
    pub fn llama_attach_threadpool(
        ctx: *mut llama_context,
        threadpool: ggml_threadpool_t,
        threadpool_batch: ggml_threadpool_t,
    );
}
extern "C" {
    pub fn llama_detach_threadpool(ctx: *mut llama_context);
}
pub type llama_model_set_tensor_data_t = ::std::option::Option<
    unsafe extern "C" fn(tensor: *mut ggml_tensor, userdata: *mut ::std::os::raw::c_void),
>;
extern "C" {
    pub fn llama_model_init_from_user(
        metadata: *mut gguf_context,
        set_tensor_data: llama_model_set_tensor_data_t,
        set_tensor_data_ud: *mut ::std::os::raw::c_void,
        params: llama_model_params,
    ) -> *mut llama_model;
}
extern "C" {
    pub fn llama_load_model_from_file(
        path_model: *const ::std::os::raw::c_char,
        params: llama_model_params,
    ) -> *mut llama_model;
}
extern "C" {
    pub fn llama_model_load_from_file(
        path_model: *const ::std::os::raw::c_char,
        params: llama_model_params,
    ) -> *mut llama_model;
}
extern "C" {
    pub fn llama_model_load_from_file_ptr(
        file: *mut FILE,
        params: llama_model_params,
    ) -> *mut llama_model;
}
extern "C" {
    pub fn llama_model_load_from_splits(
        paths: *mut *const ::std::os::raw::c_char,
        n_paths: usize,
        params: llama_model_params,
    ) -> *mut llama_model;
}
extern "C" {
    pub fn llama_model_save_to_file(
        model: *const llama_model,
        path_model: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn llama_free_model(model: *mut llama_model);
}
extern "C" {
    pub fn llama_model_free(model: *mut llama_model);
}
extern "C" {
    pub fn llama_init_from_model(
        model: *mut llama_model,
        params: llama_context_params,
    ) -> *mut llama_context;
}
extern "C" {
    pub fn llama_new_context_with_model(
        model: *mut llama_model,
        params: llama_context_params,
    ) -> *mut llama_context;
}
extern "C" {
    pub fn llama_free(ctx: *mut llama_context);
}
extern "C" {
    pub fn llama_time_us() -> i64;
}
extern "C" {
    pub fn llama_max_devices() -> usize;
}
extern "C" {
    pub fn llama_max_parallel_sequences() -> usize;
}
extern "C" {
    pub fn llama_max_tensor_buft_overrides() -> usize;
}
extern "C" {
    pub fn llama_supports_mmap() -> bool;
}
extern "C" {
    pub fn llama_supports_mlock() -> bool;
}
extern "C" {
    pub fn llama_supports_gpu_offload() -> bool;
}
extern "C" {
    pub fn llama_supports_rpc() -> bool;
}
extern "C" {
    pub fn llama_n_ctx(ctx: *const llama_context) -> u32;
}
extern "C" {
    pub fn llama_n_ctx_seq(ctx: *const llama_context) -> u32;
}
extern "C" {
    pub fn llama_n_batch(ctx: *const llama_context) -> u32;
}
extern "C" {
    pub fn llama_n_ubatch(ctx: *const llama_context) -> u32;
}
extern "C" {
    pub fn llama_n_seq_max(ctx: *const llama_context) -> u32;
}
extern "C" {
    pub fn llama_n_rs_seq(ctx: *const llama_context) -> u32;
}
extern "C" {
    pub fn llama_n_ctx_train(model: *const llama_model) -> i32;
}
extern "C" {
    pub fn llama_n_embd(model: *const llama_model) -> i32;
}
extern "C" {
    pub fn llama_n_layer(model: *const llama_model) -> i32;
}
extern "C" {
    pub fn llama_n_head(model: *const llama_model) -> i32;
}
extern "C" {
    pub fn llama_n_vocab(vocab: *const llama_vocab) -> i32;
}
extern "C" {
    pub fn llama_get_model(ctx: *const llama_context) -> *const llama_model;
}
extern "C" {
    pub fn llama_get_memory(ctx: *const llama_context) -> llama_memory_t;
}
extern "C" {
    pub fn llama_pooling_type(ctx: *const llama_context) -> llama_pooling_type;
}
extern "C" {
    pub fn llama_model_get_vocab(model: *const llama_model) -> *const llama_vocab;
}
extern "C" {
    pub fn llama_model_rope_type(model: *const llama_model) -> llama_rope_type;
}
extern "C" {
    pub fn llama_model_n_ctx_train(model: *const llama_model) -> i32;
}
extern "C" {
    pub fn llama_model_n_embd(model: *const llama_model) -> i32;
}
extern "C" {
    pub fn llama_model_n_embd_inp(model: *const llama_model) -> i32;
}
extern "C" {
    pub fn llama_model_n_embd_out(model: *const llama_model) -> i32;
}
extern "C" {
    pub fn llama_model_n_layer(model: *const llama_model) -> i32;
}
extern "C" {
    pub fn llama_model_n_layer_nextn(model: *const llama_model) -> i32;
}
extern "C" {
    pub fn llama_model_n_head(model: *const llama_model) -> i32;
}
extern "C" {
    pub fn llama_model_n_head_kv(model: *const llama_model) -> i32;
}
extern "C" {
    pub fn llama_model_n_swa(model: *const llama_model) -> i32;
}
extern "C" {
    pub fn llama_model_rope_freq_scale_train(model: *const llama_model) -> f32;
}
extern "C" {
    pub fn llama_model_n_cls_out(model: *const llama_model) -> u32;
}
extern "C" {
    pub fn llama_model_cls_label(
        model: *const llama_model,
        i: u32,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn llama_vocab_type(vocab: *const llama_vocab) -> llama_vocab_type;
}
extern "C" {
    pub fn llama_vocab_n_tokens(vocab: *const llama_vocab) -> i32;
}
extern "C" {
    pub fn llama_model_meta_val_str(
        model: *const llama_model,
        key: *const ::std::os::raw::c_char,
        buf: *mut ::std::os::raw::c_char,
        buf_size: usize,
    ) -> i32;
}
extern "C" {
    pub fn llama_model_meta_count(model: *const llama_model) -> i32;
}
extern "C" {
    pub fn llama_model_meta_key_str(key: llama_model_meta_key) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn llama_model_meta_key_by_index(
        model: *const llama_model,
        i: i32,
        buf: *mut ::std::os::raw::c_char,
        buf_size: usize,
    ) -> i32;
}
extern "C" {
    pub fn llama_model_meta_val_str_by_index(
        model: *const llama_model,
        i: i32,
        buf: *mut ::std::os::raw::c_char,
        buf_size: usize,
    ) -> i32;
}
extern "C" {
    pub fn llama_model_desc(
        model: *const llama_model,
        buf: *mut ::std::os::raw::c_char,
        buf_size: usize,
    ) -> i32;
}
extern "C" {
    pub fn llama_model_ftype(model: *const llama_model) -> llama_ftype;
}
extern "C" {
    pub fn llama_model_size(model: *const llama_model) -> u64;
}
extern "C" {
    pub fn llama_model_chat_template(
        model: *const llama_model,
        name: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn llama_model_n_params(model: *const llama_model) -> u64;
}
extern "C" {
    pub fn llama_model_has_encoder(model: *const llama_model) -> bool;
}
extern "C" {
    pub fn llama_model_has_decoder(model: *const llama_model) -> bool;
}
extern "C" {
    pub fn llama_model_decoder_start_token(model: *const llama_model) -> llama_token;
}
extern "C" {
    pub fn llama_model_is_recurrent(model: *const llama_model) -> bool;
}
extern "C" {
    pub fn llama_model_is_hybrid(model: *const llama_model) -> bool;
}
extern "C" {
    pub fn llama_model_is_diffusion(model: *const llama_model) -> bool;
}
extern "C" {
    pub fn llama_model_quantize(
        fname_inp: *const ::std::os::raw::c_char,
        fname_out: *const ::std::os::raw::c_char,
        params: *const llama_model_quantize_params,
    ) -> u32;
}
extern "C" {
    pub fn llama_adapter_lora_init(
        model: *mut llama_model,
        path_lora: *const ::std::os::raw::c_char,
    ) -> *mut llama_adapter_lora;
}
extern "C" {
    pub fn llama_adapter_meta_val_str(
        adapter: *const llama_adapter_lora,
        key: *const ::std::os::raw::c_char,
        buf: *mut ::std::os::raw::c_char,
        buf_size: usize,
    ) -> i32;
}
extern "C" {
    pub fn llama_adapter_meta_count(adapter: *const llama_adapter_lora) -> i32;
}
extern "C" {
    pub fn llama_adapter_meta_key_by_index(
        adapter: *const llama_adapter_lora,
        i: i32,
        buf: *mut ::std::os::raw::c_char,
        buf_size: usize,
    ) -> i32;
}
extern "C" {
    pub fn llama_adapter_meta_val_str_by_index(
        adapter: *const llama_adapter_lora,
        i: i32,
        buf: *mut ::std::os::raw::c_char,
        buf_size: usize,
    ) -> i32;
}
extern "C" {
    pub fn llama_adapter_lora_free(adapter: *mut llama_adapter_lora);
}
extern "C" {
    pub fn llama_adapter_get_alora_n_invocation_tokens(adapter: *const llama_adapter_lora) -> u64;
}
extern "C" {
    pub fn llama_adapter_get_alora_invocation_tokens(
        adapter: *const llama_adapter_lora,
    ) -> *const llama_token;
}
extern "C" {
    pub fn llama_set_adapters_lora(
        ctx: *mut llama_context,
        adapters: *mut *mut llama_adapter_lora,
        n_adapters: usize,
        scales: *mut f32,
    ) -> i32;
}
extern "C" {
    pub fn llama_set_adapter_cvec(
        ctx: *mut llama_context,
        data: *const f32,
        len: usize,
        n_embd: i32,
        il_start: i32,
        il_end: i32,
    ) -> i32;
}
extern "C" {
    pub fn llama_memory_clear(mem: llama_memory_t, data: bool);
}
extern "C" {
    pub fn llama_memory_seq_rm(
        mem: llama_memory_t,
        seq_id: llama_seq_id,
        p0: llama_pos,
        p1: llama_pos,
    ) -> bool;
}
extern "C" {
    pub fn llama_memory_seq_cp(
        mem: llama_memory_t,
        seq_id_src: llama_seq_id,
        seq_id_dst: llama_seq_id,
        p0: llama_pos,
        p1: llama_pos,
    );
}
extern "C" {
    pub fn llama_memory_seq_keep(mem: llama_memory_t, seq_id: llama_seq_id);
}
extern "C" {
    pub fn llama_memory_seq_add(
        mem: llama_memory_t,
        seq_id: llama_seq_id,
        p0: llama_pos,
        p1: llama_pos,
        delta: llama_pos,
    );
}
extern "C" {
    pub fn llama_memory_seq_div(
        mem: llama_memory_t,
        seq_id: llama_seq_id,
        p0: llama_pos,
        p1: llama_pos,
        d: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn llama_memory_seq_pos_min(mem: llama_memory_t, seq_id: llama_seq_id) -> llama_pos;
}
extern "C" {
    pub fn llama_memory_seq_pos_max(mem: llama_memory_t, seq_id: llama_seq_id) -> llama_pos;
}
extern "C" {
    pub fn llama_memory_can_shift(mem: llama_memory_t) -> bool;
}
extern "C" {
    pub fn llama_state_get_size(ctx: *mut llama_context) -> usize;
}
extern "C" {
    pub fn llama_get_state_size(ctx: *mut llama_context) -> usize;
}
extern "C" {
    pub fn llama_state_get_data(ctx: *mut llama_context, dst: *mut u8, size: usize) -> usize;
}
extern "C" {
    pub fn llama_copy_state_data(ctx: *mut llama_context, dst: *mut u8) -> usize;
}
extern "C" {
    pub fn llama_state_set_data(ctx: *mut llama_context, src: *const u8, size: usize) -> usize;
}
extern "C" {
    pub fn llama_set_state_data(ctx: *mut llama_context, src: *const u8) -> usize;
}
extern "C" {
    pub fn llama_state_load_file(
        ctx: *mut llama_context,
        path_session: *const ::std::os::raw::c_char,
        tokens_out: *mut llama_token,
        n_token_capacity: usize,
        n_token_count_out: *mut usize,
    ) -> bool;
}
extern "C" {
    pub fn llama_load_session_file(
        ctx: *mut llama_context,
        path_session: *const ::std::os::raw::c_char,
        tokens_out: *mut llama_token,
        n_token_capacity: usize,
        n_token_count_out: *mut usize,
    ) -> bool;
}
extern "C" {
    pub fn llama_state_save_file(
        ctx: *mut llama_context,
        path_session: *const ::std::os::raw::c_char,
        tokens: *const llama_token,
        n_token_count: usize,
    ) -> bool;
}
extern "C" {
    pub fn llama_save_session_file(
        ctx: *mut llama_context,
        path_session: *const ::std::os::raw::c_char,
        tokens: *const llama_token,
        n_token_count: usize,
    ) -> bool;
}
extern "C" {
    pub fn llama_state_seq_get_size(ctx: *mut llama_context, seq_id: llama_seq_id) -> usize;
}
extern "C" {
    pub fn llama_state_seq_get_data(
        ctx: *mut llama_context,
        dst: *mut u8,
        size: usize,
        seq_id: llama_seq_id,
    ) -> usize;
}
extern "C" {
    pub fn llama_state_seq_set_data(
        ctx: *mut llama_context,
        src: *const u8,
        size: usize,
        dest_seq_id: llama_seq_id,
    ) -> usize;
}
extern "C" {
    pub fn llama_state_seq_save_file(
        ctx: *mut llama_context,
        filepath: *const ::std::os::raw::c_char,
        seq_id: llama_seq_id,
        tokens: *const llama_token,
        n_token_count: usize,
    ) -> usize;
}
extern "C" {
    pub fn llama_state_seq_load_file(
        ctx: *mut llama_context,
        filepath: *const ::std::os::raw::c_char,
        dest_seq_id: llama_seq_id,
        tokens_out: *mut llama_token,
        n_token_capacity: usize,
        n_token_count_out: *mut usize,
    ) -> usize;
}
pub type llama_state_seq_flags = u32;
extern "C" {
    pub fn llama_state_seq_get_size_ext(
        ctx: *mut llama_context,
        seq_id: llama_seq_id,
        flags: llama_state_seq_flags,
    ) -> usize;
}
extern "C" {
    pub fn llama_state_seq_get_data_ext(
        ctx: *mut llama_context,
        dst: *mut u8,
        size: usize,
        seq_id: llama_seq_id,
        flags: llama_state_seq_flags,
    ) -> usize;
}
extern "C" {
    pub fn llama_state_seq_set_data_ext(
        ctx: *mut llama_context,
        src: *const u8,
        size: usize,
        dest_seq_id: llama_seq_id,
        flags: llama_state_seq_flags,
    ) -> usize;
}
extern "C" {
    pub fn llama_batch_get_one(tokens: *mut llama_token, n_tokens: i32) -> llama_batch;
}
extern "C" {
    pub fn llama_batch_init(n_tokens: i32, embd: i32, n_seq_max: i32) -> llama_batch;
}
extern "C" {
    pub fn llama_batch_free(batch: llama_batch);
}
extern "C" {
    pub fn llama_encode(ctx: *mut llama_context, batch: llama_batch) -> i32;
}
extern "C" {
    pub fn llama_decode(ctx: *mut llama_context, batch: llama_batch) -> i32;
}
extern "C" {
    pub fn llama_set_n_threads(ctx: *mut llama_context, n_threads: i32, n_threads_batch: i32);
}
extern "C" {
    pub fn llama_n_threads(ctx: *mut llama_context) -> i32;
}
extern "C" {
    pub fn llama_n_threads_batch(ctx: *mut llama_context) -> i32;
}
extern "C" {
    pub fn llama_set_embeddings(ctx: *mut llama_context, embeddings: bool);
}
extern "C" {
    pub fn llama_set_causal_attn(ctx: *mut llama_context, causal_attn: bool);
}
extern "C" {
    pub fn llama_set_warmup(ctx: *mut llama_context, warmup: bool);
}
extern "C" {
    pub fn llama_set_abort_callback(
        ctx: *mut llama_context,
        abort_callback: ggml_abort_callback,
        abort_callback_data: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn llama_synchronize(ctx: *mut llama_context);
}
extern "C" {
    pub fn llama_get_logits(ctx: *mut llama_context) -> *mut f32;
}
extern "C" {
    pub fn llama_get_logits_ith(ctx: *mut llama_context, i: i32) -> *mut f32;
}
extern "C" {
    pub fn llama_get_embeddings(ctx: *mut llama_context) -> *mut f32;
}
extern "C" {
    pub fn llama_get_embeddings_ith(ctx: *mut llama_context, i: i32) -> *mut f32;
}
extern "C" {
    pub fn llama_get_embeddings_seq(ctx: *mut llama_context, seq_id: llama_seq_id) -> *mut f32;
}
extern "C" {
    pub fn llama_get_sampled_token_ith(ctx: *mut llama_context, i: i32) -> llama_token;
}
extern "C" {
    pub fn llama_get_sampled_probs_ith(ctx: *mut llama_context, i: i32) -> *mut f32;
}
extern "C" {
    pub fn llama_get_sampled_probs_count_ith(ctx: *mut llama_context, i: i32) -> u32;
}
extern "C" {
    pub fn llama_get_sampled_logits_ith(ctx: *mut llama_context, i: i32) -> *mut f32;
}
extern "C" {
    pub fn llama_get_sampled_logits_count_ith(ctx: *mut llama_context, i: i32) -> u32;
}
extern "C" {
    pub fn llama_get_sampled_candidates_ith(ctx: *mut llama_context, i: i32) -> *mut llama_token;
}
extern "C" {
    pub fn llama_get_sampled_candidates_count_ith(ctx: *mut llama_context, i: i32) -> u32;
}
extern "C" {
    pub fn llama_vocab_get_text(
        vocab: *const llama_vocab,
        token: llama_token,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn llama_vocab_get_score(vocab: *const llama_vocab, token: llama_token) -> f32;
}
extern "C" {
    pub fn llama_vocab_get_attr(vocab: *const llama_vocab, token: llama_token) -> llama_token_attr;
}
extern "C" {
    pub fn llama_vocab_is_eog(vocab: *const llama_vocab, token: llama_token) -> bool;
}
extern "C" {
    pub fn llama_vocab_is_control(vocab: *const llama_vocab, token: llama_token) -> bool;
}
extern "C" {
    pub fn llama_vocab_bos(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_vocab_eos(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_vocab_eot(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_vocab_sep(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_vocab_nl(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_vocab_pad(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_vocab_mask(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_vocab_get_add_bos(vocab: *const llama_vocab) -> bool;
}
extern "C" {
    pub fn llama_vocab_get_add_eos(vocab: *const llama_vocab) -> bool;
}
extern "C" {
    pub fn llama_vocab_get_add_sep(vocab: *const llama_vocab) -> bool;
}
extern "C" {
    pub fn llama_vocab_get_suppress_tokens(
        vocab: *const llama_vocab,
        n_suppress_tokens: *mut i32,
    ) -> *const llama_token;
}
extern "C" {
    pub fn llama_vocab_fim_pre(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_vocab_fim_suf(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_vocab_fim_mid(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_vocab_fim_pad(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_vocab_fim_rep(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_vocab_fim_sep(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_token_get_text(
        vocab: *const llama_vocab,
        token: llama_token,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn llama_token_get_score(vocab: *const llama_vocab, token: llama_token) -> f32;
}
extern "C" {
    pub fn llama_token_get_attr(vocab: *const llama_vocab, token: llama_token) -> llama_token_attr;
}
extern "C" {
    pub fn llama_token_is_eog(vocab: *const llama_vocab, token: llama_token) -> bool;
}
extern "C" {
    pub fn llama_token_is_control(vocab: *const llama_vocab, token: llama_token) -> bool;
}
extern "C" {
    pub fn llama_token_bos(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_token_eos(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_token_eot(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_token_cls(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_token_sep(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_token_nl(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_token_pad(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_add_bos_token(vocab: *const llama_vocab) -> bool;
}
extern "C" {
    pub fn llama_add_eos_token(vocab: *const llama_vocab) -> bool;
}
extern "C" {
    pub fn llama_token_fim_pre(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_token_fim_suf(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_token_fim_mid(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_token_fim_pad(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_token_fim_rep(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_token_fim_sep(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    pub fn llama_vocab_cls(vocab: *const llama_vocab) -> llama_token;
}
extern "C" {
    #[doc = " @details Convert the provided text into tokens.\n @param tokens The tokens pointer must be large enough to hold the resulting tokens.\n @return Returns the number of tokens on success, no more than n_tokens_max\n @return Returns a negative number on failure - the number of tokens that would have been returned\n @return Returns INT32_MIN on overflow (e.g., tokenization result size exceeds int32_t limit)\n @param add_special Allow to add BOS and EOS tokens if model is configured to do so.\n @param parse_special Allow tokenizing special and/or control tokens which otherwise are not exposed and treated\n                      as plaintext. Does not insert a leading space."]
    pub fn llama_tokenize(
        vocab: *const llama_vocab,
        text: *const ::std::os::raw::c_char,
        text_len: i32,
        tokens: *mut llama_token,
        n_tokens_max: i32,
        add_special: bool,
        parse_special: bool,
    ) -> i32;
}
extern "C" {
    pub fn llama_token_to_piece(
        vocab: *const llama_vocab,
        token: llama_token,
        buf: *mut ::std::os::raw::c_char,
        length: i32,
        lstrip: i32,
        special: bool,
    ) -> i32;
}
extern "C" {
    #[doc = " @details Convert the provided tokens into text (inverse of llama_tokenize()).\n @param text The char pointer must be large enough to hold the resulting text.\n @return Returns the number of chars/bytes on success, no more than text_len_max.\n @return Returns a negative number on failure - the number of chars/bytes that would have been returned.\n @param remove_special Allow to remove BOS and EOS tokens if model is configured to do so.\n @param unparse_special If true, special tokens are rendered in the output."]
    pub fn llama_detokenize(
        vocab: *const llama_vocab,
        tokens: *const llama_token,
        n_tokens: i32,
        text: *mut ::std::os::raw::c_char,
        text_len_max: i32,
        remove_special: bool,
        unparse_special: bool,
    ) -> i32;
}
extern "C" {
    #[doc = " Apply chat template. Inspired by hf apply_chat_template() on python.\n\n NOTE: This function does not use a jinja parser. It only support a pre-defined list of template. See more: https://github.com/ggml-org/llama.cpp/wiki/Templates-supported-by-llama_chat_apply_template\n @param tmpl A Jinja template to use for this chat.\n @param chat Pointer to a list of multiple llama_chat_message\n @param n_msg Number of llama_chat_message in this chat\n @param add_ass Whether to end the prompt with the token(s) that indicate the start of an assistant message.\n @param buf A buffer to hold the output formatted prompt. The recommended alloc size is 2 * (total number of characters of all messages)\n @param length The size of the allocated buffer\n @return The total number of bytes of the formatted prompt. If is it larger than the size of buffer, you may need to re-alloc it and then re-apply the template."]
    pub fn llama_chat_apply_template(
        tmpl: *const ::std::os::raw::c_char,
        chat: *const llama_chat_message,
        n_msg: usize,
        add_ass: bool,
        buf: *mut ::std::os::raw::c_char,
        length: i32,
    ) -> i32;
}
extern "C" {
    pub fn llama_chat_builtin_templates(
        output: *mut *const ::std::os::raw::c_char,
        len: usize,
    ) -> i32;
}
pub type llama_sampler_context_t = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_sampler_data {
    pub logits: *mut ggml_tensor,
    pub probs: *mut ggml_tensor,
    pub sampled: *mut ggml_tensor,
    pub candidates: *mut ggml_tensor,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_sampler_i {
    pub name: ::std::option::Option<
        unsafe extern "C" fn(smpl: *const llama_sampler) -> *const ::std::os::raw::c_char,
    >,
    pub accept:
        ::std::option::Option<unsafe extern "C" fn(smpl: *mut llama_sampler, token: llama_token)>,
    pub apply: ::std::option::Option<
        unsafe extern "C" fn(smpl: *mut llama_sampler, cur_p: *mut llama_token_data_array),
    >,
    pub reset: ::std::option::Option<unsafe extern "C" fn(smpl: *mut llama_sampler)>,
    pub clone: ::std::option::Option<
        unsafe extern "C" fn(smpl: *const llama_sampler) -> *mut llama_sampler,
    >,
    pub free: ::std::option::Option<unsafe extern "C" fn(smpl: *mut llama_sampler)>,
    pub backend_init: ::std::option::Option<
        unsafe extern "C" fn(
            smpl: *mut llama_sampler,
            buft: ggml_backend_buffer_type_t,
            n_outputs_max_per_seq: u32,
        ) -> bool,
    >,
    pub backend_accept: ::std::option::Option<
        unsafe extern "C" fn(
            smpl: *mut llama_sampler,
            ctx: *mut ggml_context,
            gf: *mut ggml_cgraph,
            selected_token: *mut ggml_tensor,
        ),
    >,
    pub backend_apply: ::std::option::Option<
        unsafe extern "C" fn(
            smpl: *mut llama_sampler,
            ctx: *mut ggml_context,
            gf: *mut ggml_cgraph,
            data: *mut llama_sampler_data,
        ),
    >,
    pub backend_set_input: ::std::option::Option<unsafe extern "C" fn(smpl: *mut llama_sampler)>,
    pub backend_reset: ::std::option::Option<unsafe extern "C" fn(smpl: *mut llama_sampler)>,
    pub copy_state: ::std::option::Option<
        unsafe extern "C" fn(src: *const llama_sampler, dst: *mut llama_sampler),
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_sampler {
    pub iface: *mut llama_sampler_i,
    pub ctx: llama_sampler_context_t,
}
extern "C" {
    pub fn llama_set_sampler(
        ctx: *mut llama_context,
        seq_id: llama_seq_id,
        smpl: *mut llama_sampler,
    ) -> bool;
}
extern "C" {
    pub fn llama_sampler_init(
        iface: *mut llama_sampler_i,
        ctx: llama_sampler_context_t,
    ) -> *mut llama_sampler;
}
extern "C" {
    pub fn llama_sampler_name(smpl: *const llama_sampler) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn llama_sampler_accept(smpl: *mut llama_sampler, token: llama_token);
}
extern "C" {
    pub fn llama_sampler_apply(smpl: *mut llama_sampler, cur_p: *mut llama_token_data_array);
}
extern "C" {
    pub fn llama_sampler_reset(smpl: *mut llama_sampler);
}
extern "C" {
    pub fn llama_sampler_clone(smpl: *const llama_sampler) -> *mut llama_sampler;
}
extern "C" {
    pub fn llama_sampler_copy(src: *const llama_sampler, dst: *mut llama_sampler);
}
extern "C" {
    pub fn llama_sampler_free(smpl: *mut llama_sampler);
}
extern "C" {
    pub fn llama_sampler_chain_init(params: llama_sampler_chain_params) -> *mut llama_sampler;
}
extern "C" {
    pub fn llama_sampler_chain_add(chain: *mut llama_sampler, smpl: *mut llama_sampler);
}
extern "C" {
    pub fn llama_sampler_chain_get(chain: *mut llama_sampler, i: i32) -> *mut llama_sampler;
}
extern "C" {
    pub fn llama_sampler_chain_n(chain: *const llama_sampler) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn llama_sampler_chain_remove(chain: *mut llama_sampler, i: i32) -> *mut llama_sampler;
}
extern "C" {
    pub fn llama_sampler_init_greedy() -> *mut llama_sampler;
}
extern "C" {
    #[doc = " seed == LLAMA_DEFAULT_SEED to use a random seed."]
    pub fn llama_sampler_init_dist(seed: u32) -> *mut llama_sampler;
}
extern "C" {
    #[doc = " @details Top-K sampling described in academic paper \"The Curious Case of Neural Text Degeneration\" https://arxiv.org/abs/1904.09751\n Setting k <= 0 makes this a noop"]
    pub fn llama_sampler_init_top_k(k: i32) -> *mut llama_sampler;
}
extern "C" {
    #[doc = " @details Nucleus sampling described in academic paper \"The Curious Case of Neural Text Degeneration\" https://arxiv.org/abs/1904.09751"]
    pub fn llama_sampler_init_top_p(p: f32, min_keep: usize) -> *mut llama_sampler;
}
extern "C" {
    #[doc = " @details Minimum P sampling as described in https://github.com/ggml-org/llama.cpp/pull/3841"]
    pub fn llama_sampler_init_min_p(p: f32, min_keep: usize) -> *mut llama_sampler;
}
extern "C" {
    #[doc = " @details Locally Typical Sampling implementation described in the paper https://arxiv.org/abs/2202.00666."]
    pub fn llama_sampler_init_typical(p: f32, min_keep: usize) -> *mut llama_sampler;
}
extern "C" {
    #[doc = " #details Updates the logits l_i` = l_i/t. When t <= 0.0f, the maximum logit is kept at it's original value, the rest are set to -inf"]
    pub fn llama_sampler_init_temp(t: f32) -> *mut llama_sampler;
}
extern "C" {
    #[doc = " @details Dynamic temperature implementation (a.k.a. entropy) described in the paper https://arxiv.org/abs/2309.02772."]
    pub fn llama_sampler_init_temp_ext(t: f32, delta: f32, exponent: f32) -> *mut llama_sampler;
}
extern "C" {
    #[doc = " @details XTC sampler as described in https://github.com/oobabooga/text-generation-webui/pull/6335"]
    pub fn llama_sampler_init_xtc(p: f32, t: f32, min_keep: usize, seed: u32)
        -> *mut llama_sampler;
}
extern "C" {
    #[doc = " @details Top n sigma sampling as described in academic paper \"Top-nσ: Not All Logits Are You Need\" https://arxiv.org/pdf/2411.07641"]
    pub fn llama_sampler_init_top_n_sigma(n: f32) -> *mut llama_sampler;
}
extern "C" {
    #[doc = " @details Mirostat 1.0 algorithm described in the paper https://arxiv.org/abs/2007.14966. Uses tokens instead of words.\n @param candidates A vector of `llama_token_data` containing the candidate tokens, their probabilities (p), and log-odds (logit) for the current position in the generated text.\n @param tau  The target cross-entropy (or surprise) value you want to achieve for the generated text. A higher value corresponds to more surprising or less predictable text, while a lower value corresponds to less surprising or more predictable text.\n @param eta The learning rate used to update `mu` based on the error between the target and observed surprisal of the sampled word. A larger learning rate will cause `mu` to be updated more quickly, while a smaller learning rate will result in slower updates.\n @param m The number of tokens considered in the estimation of `s_hat`. This is an arbitrary value that is used to calculate `s_hat`, which in turn helps to calculate the value of `k`. In the paper, they use `m = 100`, but you can experiment with different values to see how it affects the performance of the algorithm.\n @param mu Maximum cross-entropy. This value is initialized to be twice the target cross-entropy (`2 * tau`) and is updated in the algorithm based on the error between the target and observed surprisal."]
    pub fn llama_sampler_init_mirostat(
        n_vocab: i32,
        seed: u32,
        tau: f32,
        eta: f32,
        m: i32,
    ) -> *mut llama_sampler;
}
extern "C" {
    #[doc = " @details Mirostat 2.0 algorithm described in the paper https://arxiv.org/abs/2007.14966. Uses tokens instead of words.\n @param candidates A vector of `llama_token_data` containing the candidate tokens, their probabilities (p), and log-odds (logit) for the current position in the generated text.\n @param tau  The target cross-entropy (or surprise) value you want to achieve for the generated text. A higher value corresponds to more surprising or less predictable text, while a lower value corresponds to less surprising or more predictable text.\n @param eta The learning rate used to update `mu` based on the error between the target and observed surprisal of the sampled word. A larger learning rate will cause `mu` to be updated more quickly, while a smaller learning rate will result in slower updates.\n @param mu Maximum cross-entropy. This value is initialized to be twice the target cross-entropy (`2 * tau`) and is updated in the algorithm based on the error between the target and observed surprisal."]
    pub fn llama_sampler_init_mirostat_v2(seed: u32, tau: f32, eta: f32) -> *mut llama_sampler;
}
extern "C" {
    #[doc = " @details Initializes a GBNF grammar, see grammars/README.md for details.\n @param vocab The vocabulary that this grammar will be used with.\n @param grammar_str The production rules for the grammar, encoded as a string. Returns an empty grammar if empty. Returns NULL if parsing of grammar_str fails.\n @param grammar_root The name of the start symbol for the grammar."]
    pub fn llama_sampler_init_grammar(
        vocab: *const llama_vocab,
        grammar_str: *const ::std::os::raw::c_char,
        grammar_root: *const ::std::os::raw::c_char,
    ) -> *mut llama_sampler;
}
extern "C" {
    pub fn llama_sampler_init_grammar_lazy(
        vocab: *const llama_vocab,
        grammar_str: *const ::std::os::raw::c_char,
        grammar_root: *const ::std::os::raw::c_char,
        trigger_words: *mut *const ::std::os::raw::c_char,
        num_trigger_words: usize,
        trigger_tokens: *const llama_token,
        num_trigger_tokens: usize,
    ) -> *mut llama_sampler;
}
extern "C" {
    #[doc = " @details Lazy grammar sampler, introduced in https://github.com/ggml-org/llama.cpp/pull/9639\n @param trigger_patterns A list of patterns that will trigger the grammar sampler. Pattern will be matched from the start of the generation output, and grammar sampler will be fed content starting from its first match group.\n @param trigger_tokens A list of tokens that will trigger the grammar sampler. Grammar sampler will be fed content starting from the trigger token included."]
    pub fn llama_sampler_init_grammar_lazy_patterns(
        vocab: *const llama_vocab,
        grammar_str: *const ::std::os::raw::c_char,
        grammar_root: *const ::std::os::raw::c_char,
        trigger_patterns: *mut *const ::std::os::raw::c_char,
        num_trigger_patterns: usize,
        trigger_tokens: *const llama_token,
        num_trigger_tokens: usize,
    ) -> *mut llama_sampler;
}
extern "C" {
    #[doc = " NOTE: Avoid using on the full vocabulary as searching for repeated tokens can become slow. For example, apply top-k or top-p sampling first."]
    pub fn llama_sampler_init_penalties(
        n_vocab: i32,
        penalty_last_n: i32,
        penalty_repeat: f32,
        penalty_freq: f32,
        penalty_present: f32,
    ) -> *mut llama_sampler;
}
extern "C" {
    #[doc = "  @details DRY sampler, designed by p-e-w, as described in: https://github.com/oobabooga/text-generation-webui/pull/5677, porting Koboldcpp implementation authored by pi6am: https://github.com/LostRuins/koboldcpp/pull/982"]
    pub fn llama_sampler_init_dry(
        vocab: *const llama_vocab,
        dry_multiplier: f32,
        dry_base: f32,
        dry_allowed_length: i32,
        dry_penalty_last_n: i32,
        seq_breakers: *mut *const ::std::os::raw::c_char,
        num_breakers: usize,
    ) -> *mut llama_sampler;
}
extern "C" {
    #[doc = " adaptive-p: select tokens near a configurable target probability over time.\n\n the adaptive-p sampler transforms the token probability distribution to favor tokens\n that fall near a user-configurable probability target.\n\n internally, the sampler maintains an exponential moving average of the *ORIGINAL*\n probabilities of selected tokens at each sampling step. it uses this EMA to compute an\n adapted target probability at each sampling step, thus maintaining the desired target\n probability over time.\n\n adaptive-p selects a token ID rather than just mutating candidates, so it must be last\n in the sampler chain (like mirostat, dist, greedy).\n\n only mild truncation before this sampler is recommended. we suggest applying min-p\n before adaptive-p as the only other active sampler in the chain.\n\n @param target select tokens near this probability (valid range 0.0 to 1.0; negative = disabled)\n @param decay  EMA decay for adaptation; history ≈ 1/(1-decay) tokens (valid range 0.0 - 0.99)\n @param seed   RNG seed\n\n ref: https://github.com/ggml-org/llama.cpp/pull/17927\n"]
    pub fn llama_sampler_init_adaptive_p(target: f32, decay: f32, seed: u32) -> *mut llama_sampler;
}
extern "C" {
    pub fn llama_sampler_init_logit_bias(
        n_vocab: i32,
        n_logit_bias: i32,
        logit_bias: *const llama_logit_bias,
    ) -> *mut llama_sampler;
}
extern "C" {
    pub fn llama_sampler_init_infill(vocab: *const llama_vocab) -> *mut llama_sampler;
}
extern "C" {
    pub fn llama_sampler_get_seed(smpl: *const llama_sampler) -> u32;
}
extern "C" {
    pub fn llama_sampler_sample(
        smpl: *mut llama_sampler,
        ctx: *mut llama_context,
        idx: i32,
    ) -> llama_token;
}
extern "C" {
    #[doc = " @details Build a split GGUF final path for this chunk.\n          llama_split_path(split_path, sizeof(split_path), \"/models/ggml-model-q4_0\", 2, 4) => split_path = \"/models/ggml-model-q4_0-00002-of-00004.gguf\""]
    pub fn llama_split_path(
        split_path: *mut ::std::os::raw::c_char,
        maxlen: usize,
        path_prefix: *const ::std::os::raw::c_char,
        split_no: i32,
        split_count: i32,
    ) -> i32;
}
extern "C" {
    #[doc = " @details Extract the path prefix from the split_path if and only if the split_no and split_count match.\n          llama_split_prefix(split_prefix, 64, \"/models/ggml-model-q4_0-00002-of-00004.gguf\", 2, 4) => split_prefix = \"/models/ggml-model-q4_0\""]
    pub fn llama_split_prefix(
        split_prefix: *mut ::std::os::raw::c_char,
        maxlen: usize,
        split_path: *const ::std::os::raw::c_char,
        split_no: i32,
        split_count: i32,
    ) -> i32;
}
extern "C" {
    pub fn llama_print_system_info() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn llama_log_get(
        log_callback: *mut ggml_log_callback,
        user_data: *mut *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn llama_log_set(log_callback: ggml_log_callback, user_data: *mut ::std::os::raw::c_void);
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_perf_context_data {
    pub t_start_ms: f64,
    pub t_load_ms: f64,
    pub t_p_eval_ms: f64,
    pub t_eval_ms: f64,
    pub n_p_eval: i32,
    pub n_eval: i32,
    pub n_reused: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_perf_sampler_data {
    pub t_sample_ms: f64,
    pub n_sample: i32,
}
extern "C" {
    pub fn llama_perf_context(ctx: *const llama_context) -> llama_perf_context_data;
}
extern "C" {
    pub fn llama_perf_context_print(ctx: *const llama_context);
}
extern "C" {
    pub fn llama_perf_context_reset(ctx: *mut llama_context);
}
extern "C" {
    pub fn llama_perf_sampler(chain: *const llama_sampler) -> llama_perf_sampler_data;
}
extern "C" {
    pub fn llama_perf_sampler_print(chain: *const llama_sampler);
}
extern "C" {
    pub fn llama_perf_sampler_reset(chain: *mut llama_sampler);
}
pub type llama_opt_param_filter = ::std::option::Option<
    unsafe extern "C" fn(tensor: *const ggml_tensor, userdata: *mut ::std::os::raw::c_void) -> bool,
>;
extern "C" {
    pub fn llama_opt_param_filter_all(
        tensor: *const ggml_tensor,
        userdata: *mut ::std::os::raw::c_void,
    ) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct llama_opt_params {
    pub n_ctx_train: u32,
    pub param_filter: llama_opt_param_filter,
    pub param_filter_ud: *mut ::std::os::raw::c_void,
    pub get_opt_pars: ggml_opt_get_optimizer_params,
    pub get_opt_pars_ud: *mut ::std::os::raw::c_void,
    pub optimizer_type: ggml_opt_optimizer_type,
}
extern "C" {
    pub fn llama_opt_init(
        lctx: *mut llama_context,
        model: *mut llama_model,
        lopt_params: llama_opt_params,
    );
}
extern "C" {
    pub fn llama_opt_epoch(
        lctx: *mut llama_context,
        dataset: ggml_opt_dataset_t,
        result_train: ggml_opt_result_t,
        result_eval: ggml_opt_result_t,
        idata_split: i64,
        callback_train: ggml_opt_epoch_callback,
        callback_eval: ggml_opt_epoch_callback,
    );
}
