/* automatically generated by rust-bindgen 0.72.1 */

use crate::*;

pub const MTMD_INPUT_CHUNK_TYPE_TEXT: mtmd_input_chunk_type = 0;
pub const MTMD_INPUT_CHUNK_TYPE_IMAGE: mtmd_input_chunk_type = 1;
pub const MTMD_INPUT_CHUNK_TYPE_AUDIO: mtmd_input_chunk_type = 2;
pub const MTMD_INPUT_CHUNK_TYPE_COUNT: mtmd_input_chunk_type = 3;
pub type mtmd_input_chunk_type = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mtmd_context {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mtmd_bitmap {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mtmd_image_tokens {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mtmd_input_chunk {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mtmd_input_chunks {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mtmd_batch {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct mtmd_input_text {
    pub text: *const ::std::os::raw::c_char,
    pub text_len: usize,
    pub add_special: bool,
    pub parse_special: bool,
}
pub type mtmd_progress_callback = ::std::option::Option<
    unsafe extern "C" fn(progress: f32, user_data: *mut ::std::os::raw::c_void) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct mtmd_context_params {
    pub use_gpu: bool,
    pub print_timings: bool,
    pub n_threads: ::std::os::raw::c_int,
    pub image_marker: *const ::std::os::raw::c_char,
    pub media_marker: *const ::std::os::raw::c_char,
    pub flash_attn_type: llama_flash_attn_type,
    pub warmup: bool,
    pub image_min_tokens: ::std::os::raw::c_int,
    pub image_max_tokens: ::std::os::raw::c_int,
    pub cb_eval: ggml_backend_sched_eval_callback,
    pub cb_eval_user_data: *mut ::std::os::raw::c_void,
    pub batch_max_tokens: i32,
    pub progress_callback: mtmd_progress_callback,
    pub progress_callback_user_data: *mut ::std::os::raw::c_void,
}
extern "C" {
    pub fn mtmd_default_marker() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn mtmd_context_params_default() -> mtmd_context_params;
}
extern "C" {
    pub fn mtmd_init_from_file(
        mmproj_fname: *const ::std::os::raw::c_char,
        text_model: *const llama_model,
        ctx_params: mtmd_context_params,
    ) -> *mut mtmd_context;
}
extern "C" {
    pub fn mtmd_free(ctx: *mut mtmd_context);
}
extern "C" {
    pub fn mtmd_decode_use_non_causal(
        ctx: *const mtmd_context,
        chunk: *const mtmd_input_chunk,
    ) -> bool;
}
extern "C" {
    pub fn mtmd_decode_use_mrope(ctx: *const mtmd_context) -> bool;
}
extern "C" {
    pub fn mtmd_support_vision(ctx: *const mtmd_context) -> bool;
}
extern "C" {
    pub fn mtmd_support_audio(ctx: *const mtmd_context) -> bool;
}
extern "C" {
    pub fn mtmd_get_audio_sample_rate(ctx: *const mtmd_context) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mtmd_get_marker(ctx: *const mtmd_context) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn mtmd_bitmap_init(
        nx: u32,
        ny: u32,
        data: *const ::std::os::raw::c_uchar,
    ) -> *mut mtmd_bitmap;
}
extern "C" {
    pub fn mtmd_bitmap_init_from_audio(n_samples: usize, data: *const f32) -> *mut mtmd_bitmap;
}
extern "C" {
    pub fn mtmd_bitmap_get_nx(bitmap: *const mtmd_bitmap) -> u32;
}
extern "C" {
    pub fn mtmd_bitmap_get_ny(bitmap: *const mtmd_bitmap) -> u32;
}
extern "C" {
    pub fn mtmd_bitmap_get_data(bitmap: *const mtmd_bitmap) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn mtmd_bitmap_get_n_bytes(bitmap: *const mtmd_bitmap) -> usize;
}
extern "C" {
    pub fn mtmd_bitmap_is_audio(bitmap: *const mtmd_bitmap) -> bool;
}
extern "C" {
    pub fn mtmd_bitmap_free(bitmap: *mut mtmd_bitmap);
}
extern "C" {
    pub fn mtmd_bitmap_get_id(bitmap: *const mtmd_bitmap) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn mtmd_bitmap_set_id(bitmap: *mut mtmd_bitmap, id: *const ::std::os::raw::c_char);
}
pub type mtmd_bitmap_lazy_callback = ::std::option::Option<
    unsafe extern "C" fn(
        chunk_idx: usize,
        user_data: *mut ::std::os::raw::c_void,
        out_bitmap: *mut *mut mtmd_bitmap,
        out_text: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
>;
extern "C" {
    pub fn mtmd_bitmap_init_lazy(
        ctx: *mut mtmd_context,
        id: *const ::std::os::raw::c_char,
        user_data: *mut ::std::os::raw::c_void,
        callback: mtmd_bitmap_lazy_callback,
    ) -> *mut mtmd_bitmap;
}
extern "C" {
    pub fn mtmd_input_chunks_init() -> *mut mtmd_input_chunks;
}
extern "C" {
    pub fn mtmd_input_chunks_size(chunks: *const mtmd_input_chunks) -> usize;
}
extern "C" {
    pub fn mtmd_input_chunks_get(
        chunks: *const mtmd_input_chunks,
        idx: usize,
    ) -> *const mtmd_input_chunk;
}
extern "C" {
    pub fn mtmd_input_chunks_free(chunks: *mut mtmd_input_chunks);
}
extern "C" {
    pub fn mtmd_input_chunk_get_type(chunk: *const mtmd_input_chunk) -> mtmd_input_chunk_type;
}
extern "C" {
    pub fn mtmd_input_chunk_get_tokens_text(
        chunk: *const mtmd_input_chunk,
        n_tokens_output: *mut usize,
    ) -> *const llama_token;
}
extern "C" {
    pub fn mtmd_input_chunk_get_tokens_image(
        chunk: *const mtmd_input_chunk,
    ) -> *const mtmd_image_tokens;
}
extern "C" {
    pub fn mtmd_input_chunk_get_n_tokens(chunk: *const mtmd_input_chunk) -> usize;
}
extern "C" {
    pub fn mtmd_input_chunk_get_id(chunk: *const mtmd_input_chunk)
        -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn mtmd_input_chunk_get_n_pos(chunk: *const mtmd_input_chunk) -> llama_pos;
}
extern "C" {
    pub fn mtmd_input_chunk_copy(chunk: *const mtmd_input_chunk) -> *mut mtmd_input_chunk;
}
extern "C" {
    pub fn mtmd_input_chunk_free(chunk: *mut mtmd_input_chunk);
}
extern "C" {
    pub fn mtmd_input_chunk_save(
        chunk: *const mtmd_input_chunk,
        out_buf: *mut ::std::os::raw::c_char,
        out_len: usize,
        expected_out_len: *mut usize,
    ) -> i32;
}
extern "C" {
    pub fn mtmd_input_chunk_load(
        buf: *const ::std::os::raw::c_char,
        len: usize,
    ) -> *mut mtmd_input_chunk;
}
extern "C" {
    pub fn mtmd_image_tokens_get_n_tokens(image_tokens: *const mtmd_image_tokens) -> usize;
}
extern "C" {
    pub fn mtmd_image_tokens_get_id(
        image_tokens: *const mtmd_image_tokens,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn mtmd_image_tokens_get_n_pos(image_tokens: *const mtmd_image_tokens) -> llama_pos;
}
extern "C" {
    pub fn mtmd_image_tokens_get_nx(image_tokens: *const mtmd_image_tokens) -> usize;
}
extern "C" {
    pub fn mtmd_image_tokens_get_ny(image_tokens: *const mtmd_image_tokens) -> usize;
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct mtmd_decoder_pos {
    pub t: u32,
    pub x: u32,
    pub y: u32,
    pub z: u32,
}
extern "C" {
    pub fn mtmd_image_tokens_get_decoder_pos(
        image_tokens: *const mtmd_image_tokens,
        pos_0: llama_pos,
        i: usize,
    ) -> mtmd_decoder_pos;
}
extern "C" {
    pub fn mtmd_tokenize(
        ctx: *mut mtmd_context,
        output: *mut mtmd_input_chunks,
        text: *const mtmd_input_text,
        bitmaps: *mut *const mtmd_bitmap,
        n_bitmaps: usize,
    ) -> i32;
}
extern "C" {
    pub fn mtmd_encode(ctx: *mut mtmd_context, image_tokens: *const mtmd_image_tokens) -> i32;
}
extern "C" {
    pub fn mtmd_encode_chunk(ctx: *mut mtmd_context, chunk: *const mtmd_input_chunk) -> i32;
}
extern "C" {
    pub fn mtmd_get_output_embd(ctx: *mut mtmd_context) -> *mut f32;
}
extern "C" {
    pub fn mtmd_batch_init(ctx: *mut mtmd_context) -> *mut mtmd_batch;
}
extern "C" {
    pub fn mtmd_batch_free(batch: *mut mtmd_batch);
}
extern "C" {
    pub fn mtmd_batch_add_chunk(batch: *mut mtmd_batch, chunk: *const mtmd_input_chunk) -> i32;
}
extern "C" {
    pub fn mtmd_batch_encode(batch: *mut mtmd_batch) -> i32;
}
extern "C" {
    pub fn mtmd_batch_get_output_embd(
        batch: *mut mtmd_batch,
        chunk: *const mtmd_input_chunk,
    ) -> *mut f32;
}
extern "C" {
    pub fn mtmd_log_set(log_callback: ggml_log_callback, user_data: *mut ::std::os::raw::c_void);
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct mtmd_caps {
    pub inp_vision: bool,
    pub inp_audio: bool,
}
extern "C" {
    pub fn mtmd_get_cap_from_file(mmproj_fname: *const ::std::os::raw::c_char) -> mtmd_caps;
}
pub const MTMD_GEN_AUDIO_TYPE_NONE: mtmd_gen_audio_type = 0;
pub const MTMD_GEN_AUDIO_TYPE_QWEN3TTS: mtmd_gen_audio_type = 1;
pub const MTMD_GEN_AUDIO_TYPE_POCKETTTS: mtmd_gen_audio_type = 2;
pub type mtmd_gen_audio_type = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct mtmd_gen_audio_info {
    pub type_: mtmd_gen_audio_type,
    pub sample_rate: i32,
    pub model_variant: *const ::std::os::raw::c_char,
}
extern "C" {
    pub fn mtmd_gen_audio_get_info(ctx: *const mtmd_context) -> mtmd_gen_audio_info;
}
pub const MTMD_GEN_PROCESS_TYPE_GEN_CODE: mtmd_gen_process_type = 0;
pub const MTMD_GEN_PROCESS_TYPE_GEN_WAV: mtmd_gen_process_type = 1;
pub type mtmd_gen_process_type = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct mtmd_gen_inp {
    pub type_: mtmd_gen_process_type,
    pub code0: i32,
    pub embd: *mut f32,
    pub top_k: i32,
    pub top_p: f32,
    pub seed: u32,
    pub temp: f32,
    pub codes: *mut i32,
    pub n_codes: usize,
    pub feats: *const f32,
    pub n_feats: usize,
    pub state_data: *const ::std::os::raw::c_char,
    pub state_size: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct mtmd_gen_out {
    pub codes: *const i32,
    pub n_codes: usize,
    pub feats: *const f32,
    pub n_feats: usize,
    pub embd: *const f32,
    pub is_eos: bool,
    pub audio: *const f32,
    pub n_samples: usize,
    pub state_data: *const ::std::os::raw::c_char,
    pub state_size: usize,
}
extern "C" {
    pub fn mtmd_gen_inp_default(ctx: *const mtmd_context) -> mtmd_gen_inp;
}
extern "C" {
    pub fn mtmd_gen_audio_process(
        ctx: *mut mtmd_context,
        inp: *const mtmd_gen_inp,
        out: *mut mtmd_gen_out,
    ) -> i32;
}
extern "C" {
    pub fn mtmd_test_create_input_chunks() -> *mut mtmd_input_chunks;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mtmd_helper_video {
    _unused: [u8; 0],
}
extern "C" {
    pub fn mtmd_helper_log_set(
        log_callback: ggml_log_callback,
        user_data: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn mtmd_helper_support_video(ctx: *mut mtmd_context) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct mtmd_helper_bitmap_wrapper {
    pub bitmap: *mut mtmd_bitmap,
    pub video_ctx: *mut mtmd_helper_video,
}
extern "C" {
    pub fn mtmd_helper_bitmap_init_from_file(
        ctx: *mut mtmd_context,
        fname: *const ::std::os::raw::c_char,
        placeholder: bool,
    ) -> mtmd_helper_bitmap_wrapper;
}
extern "C" {
    pub fn mtmd_helper_bitmap_init_from_buf(
        ctx: *mut mtmd_context,
        buf: *const ::std::os::raw::c_uchar,
        len: usize,
        placeholder: bool,
    ) -> mtmd_helper_bitmap_wrapper;
}
extern "C" {
    pub fn mtmd_helper_get_n_tokens(chunks: *const mtmd_input_chunks) -> usize;
}
extern "C" {
    pub fn mtmd_helper_get_n_pos(chunks: *const mtmd_input_chunks) -> llama_pos;
}
extern "C" {
    pub fn mtmd_helper_image_get_decoder_pos(
        image: *const mtmd_image_tokens,
        pos_0: llama_pos,
        out_pos: *mut mtmd_decoder_pos,
    );
}
extern "C" {
    pub fn mtmd_helper_eval_chunks(
        ctx: *mut mtmd_context,
        lctx: *mut llama_context,
        chunks: *const mtmd_input_chunks,
        n_past: llama_pos,
        seq_id: llama_seq_id,
        n_batch: i32,
        logits_last: bool,
        new_n_past: *mut llama_pos,
    ) -> i32;
}
extern "C" {
    pub fn mtmd_helper_eval_chunk_single(
        ctx: *mut mtmd_context,
        lctx: *mut llama_context,
        chunk: *const mtmd_input_chunk,
        n_past: llama_pos,
        seq_id: llama_seq_id,
        n_batch: i32,
        logits_last: bool,
        new_n_past: *mut llama_pos,
    ) -> i32;
}
pub type mtmd_helper_post_decode_callback = ::std::option::Option<
    unsafe extern "C" fn(batch: llama_batch, user_data: *mut ::std::os::raw::c_void) -> i32,
>;
extern "C" {
    pub fn mtmd_helper_decode_image_chunk(
        ctx: *mut mtmd_context,
        lctx: *mut llama_context,
        chunk: *const mtmd_input_chunk,
        encoded_embd: *mut f32,
        n_past: llama_pos,
        seq_id: llama_seq_id,
        n_batch: i32,
        new_n_past: *mut llama_pos,
        callback: mtmd_helper_post_decode_callback,
        user_data: *mut ::std::os::raw::c_void,
    ) -> i32;
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct mtmd_helper_video_info {
    pub width: u32,
    pub height: u32,
    pub fps: f32,
    pub n_frames: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct mtmd_helper_video_init_params {
    pub fps_target: f32,
    pub ffmpeg_bin_dir: *const ::std::os::raw::c_char,
    pub timestamp_interval_ms: i64,
}
extern "C" {
    pub fn mtmd_helper_video_init_params_default() -> mtmd_helper_video_init_params;
}
extern "C" {
    pub fn mtmd_helper_video_init(
        mctx: *mut mtmd_context,
        path: *const ::std::os::raw::c_char,
        params: mtmd_helper_video_init_params,
    ) -> *mut mtmd_helper_video;
}
extern "C" {
    pub fn mtmd_helper_video_init_from_buf(
        mctx: *mut mtmd_context,
        buf: *const ::std::os::raw::c_uchar,
        len: usize,
        params: mtmd_helper_video_init_params,
    ) -> *mut mtmd_helper_video;
}
extern "C" {
    pub fn mtmd_helper_video_free(ctx: *mut mtmd_helper_video);
}
extern "C" {
    pub fn mtmd_helper_video_get_info(ctx: *const mtmd_helper_video) -> mtmd_helper_video_info;
}
extern "C" {
    pub fn mtmd_helper_video_read_next(
        ctx: *mut mtmd_helper_video,
        out_bitmap: *mut *mut mtmd_bitmap,
        out_text: *mut *mut ::std::os::raw::c_char,
    ) -> i32;
}
extern "C" {
    pub fn mtmd_helper_model_can_chat(lctx: *mut llama_context, mctx: *mut mtmd_context) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mtmd_helper_gen_audio {
    _unused: [u8; 0],
}
pub const MTMD_HELPER_GEN_AUDIO_OUTTYPE_PCM: mtmd_helper_gen_audio_outtype = 0;
pub const MTMD_HELPER_GEN_AUDIO_OUTTYPE_WAV: mtmd_helper_gen_audio_outtype = 1;
pub type mtmd_helper_gen_audio_outtype = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct mtmd_helper_gen_audio_inp {
    pub seq_id: llama_seq_id,
    pub prompt: *const ::std::os::raw::c_char,
    pub prompt_len: usize,
    pub speaker_ref: *mut mtmd_bitmap,
    pub lang: *const ::std::os::raw::c_char,
    pub top_k: i32,
    pub top_p: f32,
    pub seed: u32,
    pub out_type: mtmd_helper_gen_audio_outtype,
}
extern "C" {
    pub fn mtmd_helper_gen_audio_init(
        lctx: *mut llama_context,
        mctx: *mut mtmd_context,
    ) -> *mut mtmd_helper_gen_audio;
}
extern "C" {
    pub fn mtmd_helper_gen_audio_free(ctx: *mut mtmd_helper_gen_audio);
}
extern "C" {
    pub fn mtmd_helper_gen_audio_reset(ctx: *mut mtmd_helper_gen_audio);
}
extern "C" {
    pub fn mtmd_helper_gen_audio_set_input(
        ctx: *mut mtmd_helper_gen_audio,
        inp: *const mtmd_helper_gen_audio_inp,
    ) -> i32;
}
extern "C" {
    pub fn mtmd_helper_gen_audio_step_prompt(ctx: *mut mtmd_helper_gen_audio, n_batch: i32) -> i32;
}
extern "C" {
    pub fn mtmd_helper_gen_audio_step_gen(
        ctx: *mut mtmd_helper_gen_audio,
        sampled: llama_token,
        h_state_in: *const f32,
        h_state_out: *mut *const f32,
        out_stop: *mut bool,
    ) -> i32;
}
extern "C" {
    pub fn mtmd_helper_gen_audio_get_output(
        ctx: *mut mtmd_helper_gen_audio,
        out_sample_rate: *mut i32,
        out_data: *mut *const ::std::os::raw::c_char,
        out_data_len: *mut usize,
        out_n_samples: *mut i64,
    ) -> i32;
}
