pub mod apply_chat_template_error;
pub mod bracketed_args_failure;
pub mod chat_template_error;
pub mod decode_error;
pub mod embeddings_error;
pub mod encode_error;
pub mod eval_multimodal_chunks_error;
pub mod fit_error;
pub mod grammar_error;
pub mod grammar_runtime_error;
pub mod json_object_failure;
pub mod json_schema_to_grammar_error;
pub mod key_value_xml_tags_failure;
pub mod kv_cache_seq_add_error;
pub mod kv_cache_seq_div_error;
pub mod llama_context_load_error;
pub mod llama_cpp_error;
pub mod llama_lora_adapter_init_error;
pub mod llama_lora_adapter_remove_error;
pub mod llama_lora_adapter_set_error;
pub mod llama_model_load_error;
pub mod logits_error;
pub mod marker_detection_error;
pub mod meta_val_error;
pub mod model_params_error;
pub mod new_llama_chat_message_error;
pub mod paired_quote_failure;
pub mod parse_chat_message_error;
pub mod sample_error;
pub mod sampler_accept_error;
pub mod sampler_apply_error;
pub mod sampling_error;
pub mod string_to_token_error;
pub mod token_sampling_error;
pub mod token_to_string_error;
pub mod tool_call_format_failure;
pub mod xml_function_tags_failure;

use crate::error::llama_cpp_error::LlamaCppError;

pub type Result<TValue> = std::result::Result<TValue, LlamaCppError>;
