[package]
name = "rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
llama-cpp-2 = { path = "../../llama-cpp-2", features = ["rpc"] }
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }