name: Llama Cpp Rs Check

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  check:
    name: Run Tests on LLama Cpp Rs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: recursive
      - name: Install Compile Deps
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo apt-get update && sudo apt-get install -y build-essential curl libssl-dev libclang-dev pkg-config cmake git
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy -vv
      - name: Fmt
        run: cargo fmt --check
      - name: Build
        run: cargo build --features sampler,mtmd,llguidance -vv
      - name: Test
        run: cargo test --features sampler,mtmd,llguidance
      - name: Dry-Run Publishing
        run: RUST_BACKTRACE=1 cargo publish --workspace --verbose --dry-run
  arm64:
    name: Check that it builds on various targets (${{ matrix.name }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - name: linux/arm64
            runner: ubuntu-26.04-arm
            cuda-repo: ubuntu2604/sbsa
          - name: linux/amd64
            runner: ubuntu-26.04 # x86_64
            cuda-repo: ubuntu2604/x86_64
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: recursive
      - name: Install Compile Deps
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo apt-get update && sudo apt-get install -y build-essential curl libssl-dev libclang-dev pkg-config cmake git
      - name: Install CUDA Toolkit
        run: |
          curl -fsSLO https://developer.download.nvidia.com/compute/cuda/repos/${{ matrix.cuda-repo }}/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get install -y cuda-toolkit-13-4
          echo "/usr/local/cuda/bin" >> "$GITHUB_PATH"
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --bin simple --features cuda -vv
  mac:
    name: Check that it builds on mac
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: recursive
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --features sampler,mtmd,llguidance -vv
  windows:
    name: Check that it builds on windows
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: recursive
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --features sampler,mtmd,llguidance -vv
      - name: Test
        run: cargo test --features sampler,mtmd,llguidance
