name: unit-tests

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    name: formatting
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/install-rust-toolchain

      - run: make fmt.check

  test:
    name: tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash
    env:
      LLAMA_DISABLE_CCACHE: '1'
      RUST_BACKTRACE: '1'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/install-build-dependencies

      - uses: ./.github/actions/install-rust-toolchain

      - run: make test.unit
